spring.application.name=parcial2

# Conexión a la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/centromedico
spring.datasource.username=postgres
spring.datasource.password=11031416&
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Para que Swagger y la consola no tengan conflictos de rutas
spring.mvc.pathmatch.matching-strategy=ant_path_matcher


